### ISSUE TITLE
Add a scale bar ornament

### ISSUE THREAD

**Issue by sargunv** [sargunv/maplibre-compose#13]
The iOS SDK has a scale bar: https://maplibre.org/maplibre-native/ios/latest/documentation/maplibre/mlnmapview/scalebar/

The Android SDK has a scale bar via a plugin: https://github.com/maplibre/maplibre-plugins-android/tree/main/plugin-scalebar

We should provide this as one of the four ornaments

**Comment by westnordost** [comment]
**(Opinion:)** Given that a C API for MapLibre Native is planned on which it would be convenient to base this library on in the long term for better performance and lower footprint (instead of each the Android and iOS versions), it might be worth considering to implement this instead as a **pure Compose widget**.

As the scalebar is implemented not in native code but on each platform separately, an implementation in Compose would latest be necessary when migrating to use that to-be-released C API, hence, doing it right away means less work overall.
Additionally, in light of #24 and #25, it is an open question whether MapLibre-JS and desktop also feature a scale bar.

Furthermore, if the scale bar is just a normal compose widget, it would allow more flexibility on how and where to place it and no extra sausages regarding the API.

Minus the plugin-boilerplate, the Java Android implementation of the scale bar is about 500 lines of code, I'd estimate it to be about 300 with Kotlin and Compose.

**Comment by sargunv** [comment]
JS has a scale bar: https://www.maplibre.org/maplibre-gl-js/docs/API/classes/ScaleControl/

Native desktop I presume does not.

There's two different approaches we could take here: 

1. Building a maps SDK for Compose, wrapping what's useful from MapLibre and replacing what's better done in Compose
2. Building a MapLibre wrapper for Compose, exposing as much MapLibre functionality as possible in a form suitable for use in Compose

I think long term, (1) is the better approach, and would involve reimplementing platform functionality like the scale bar, compass, attribution icon, logo, etc. But short term, (2) should be the focus. The user can already overlay whatever composables they like on the map if they don't like the SDK's ornaments.

Flexibility of placement is an interesting problem that probably deserves an issue of its own. Rn both platforms support placement on any corner. That's ofc pretty limited. What kind of placement would be good if we didn't have platform limitations? Is it possible to expose some more flexibility here without replacing the platform ornaments? (iOS at least has support for padding per ornament)

**Comment by sargunv** [comment]
https://github.com/sargunv/maplibre-compose/pull/123
