### ISSUE TITLE
Support interaction with base style layers

### ISSUE THREAD

**Issue by sargunv** [sargunv/maplibre-compose#23]
Currently the user can configure `onClick` for layers they've added via the layer composition:

```kt
MapLibreMap {
  CircleLayer(
    ..
    onClick = { .. }
  )
}
```

But we should also have support for this on base style layers (for example, clicking on POIs defined in the base style). Unsure of the best API for this; some options:

Composables in the layer composition to represent base style layers for certain properties. This could also be reused to manage common properties like `visible`:

```kt
MapLibreMap {
  CircleLayer(
    ..
    onClick = { .. }
  )
  LayerProxy(
    id = "some-base-layer",
    onClick = { .. }
  )
}
```

Alternatively, an `onClick` handler on the map itself, with an `event` exposing click position and layer features. In this case, do we additionally allow clicking on layers in the composition (resulting in two `onClick` APIs for them)? Do we instead remove the current `onClick` API?

```kt
MapLibreMap(
  clickable = listOf("some-base-layer"),
  onClick = { event -> .. }
) {
  CircleLayer(
    ..
    onClick = { .. }
  )
}
```

Vaguely relevant: https://github.com/sargunv/maplibre-compose/issues/18

**Comment by westnordost** [comment]
> Alternatively, an `onClick` handler on the map itself, with an `event` exposing click position and layer features. In this case, do we additionally allow clicking on layers in the composition (resulting in two `onClick` APIs for them)? Do we instead remove the current `onClick` API?

The onClick handlers on the layer definition themselves are convenient because they allow better code separation: When you have a custom layer which should lead to custom behavior, you can easily put that stuff into another file / composable without having to put logic associated with that layer somewhere else (i.e. the onClick listener of the MapLibreMap composable).

On the other hand, it seems that the current API already now lacks the ability to consume the event (i.e. block it being called for the layer below).

Another thing that is not possible with the current API is something I use for my app, which is to query features not for a clicked point, but a circle with a certain radius (i.e. the finger) around the clicked point, see also https://github.com/maplibre/maplibre-native/issues/2781

---

A solution that already works now (,right?) is to overwrite the layer from the base style with a definition in code. For a probably rather rare use case, this solution is still very straightforward and will only require duplicating the style of _one_ layer from the base style.

**Comment by sargunv** [comment]
> A solution that already works now (,right?) is to overwrite the layer from the base style with a definition in code. For a probably rather rare use case, this solution is still very straightforward and will only require duplicating the style of one layer from the base style.

Yup, this workaround already exists. 

> Another thing that is not possible with the current API is something I use for my app, which is to query features not for a clicked point, but a circle with a certain radius (i.e. the finger) around the clicked point

Do you have ideas on what this API could look like on the Layer composable?

I saw the query by rect doesn't sort by distance, but ideally I'd like the API (or the default one at least) to keep sorting by distance. 

> On the other hand, it seems that the current API already now lacks the ability to consume the event (i.e. block it being called for the layer below).

What would be a reasonable iteration order? Actual order in the map style? Is it reasonable to iterate all layers in a map to achieve that order? (We only query if the layer has registered a click handler) 

Order in the composition could differ from actual order in the style due to anchoring.

**Comment by westnordost** [comment]
> Do you have ideas on what this API could look like on the Layer composable?

> I saw the query by rect doesn't sort by distance, but ideally I'd like the API (or the default one at least) to keep sorting by distance.

I think the best would be to have the radius for the circle around the clicked point as a global (MapLibreMap-global) setting, i.e. a parameter to the `MapLibreMap` composable rather than the individual Layer. (I can't think of a use case for having this radius differ per-layer.) In any case, it would need to be a parameter to the composable.
Then, of course, the returned features should always be sorted by distance to the point so that `features.first()` always returns the one closest to the tap, and that's not conveniently possible yet, so I'd say "nevermind", for now.

> What would be a reasonable iteration order?

Same as in any UI framework: What's rendered in front gets the event first

> What if one layer consumes the event, but another had a feature closer to the tap?

Good question. I think what's in front beats what's closer. If the specified "butter finger radius" for a layer that consists of polylines is dialed up to 16dp, it means that the effective width for clicks of such lines is 32dp, so even if something else is visible right next to that line, I think the polylines-layer should consume it.

**Comment by sargunv** [comment]
Cool, so I think a reasonable approach:

* Define a "low level" API directly exposing MapLibre functionality for interaction. The user will have the most flexibility here. 
* Define a "high level" API with some opinionated form of that functionality for Compose. Less flexibility, but we handle the common cases in the most ergonomic way. 

For the low level, it's enough to provide an on click handler on the map, and a separate API for querying the map in whatever ways MapLibre supports.

And then for the high level, we have the on click handlers on the layers. These will additionally have a parameter for click radius (todo, verify maplibre sorts click results when querying a circle instead of a point)

The low level (map) handler gets the event before the high level (layer) handlers. But then the iteration order between layers is from top to bottom in the map style.

**Comment by westnordost** [comment]
> todo, verify maplibre sorts click results when querying a circle instead of a point

Querying circles is a missing feature in MapLibre-native, see https://github.com/maplibre/maplibre-native/issues/2781, that's why I wrote "nevermind" regarding the whole topic of click radius.

**Comment by sargunv** [comment]
Ah I see. Hopefully that can be added upstream so we can add click radius. Does the rest of the approach described above seem reasonable?

For non-line layers, perhaps one could work around the radius issue with a second, opacity=0, circle layer on the tappable features (also possibly a viable way to handle taps on base layers without even mimicking the base style). Unsure if maplibre treats opacity=0 as visible but if it does, should be handy
